linters:
  disable-all: true
  enable:
    # - errcheck # MEMO: 今回は一旦無効化
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - misspell
issues:
  exclude:
    - '\bif block ends with a return statement\b'
    - '\bcomment on exported\b'
    - \bexported \w+ (\S*['.]*)([a-zA-Z'.*]*) should have comment or be unexported\b
    - '\bmethod ToSql should be ToSQL\b'
  exclude-dirs:
    - vendor
