name: CI

on:
  push:
  pull_request:
    branches:
      - main

# WIP
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Docker compose up
      run: docker-compose up -d

    - name: Run tests
      run: docker compose exec web make test

    - name: Stop and remove docker containers
      run: docker-compose down
      if: always()
