name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22

    - name: Install dependencies
      run: make mod

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
      env:
        GOPATH: ${{ runner.temp }}/go

    - name: Add golangci-lint to PATH
      run: echo "${{ runner.temp }}/go/bin" >> $GITHUB_PATH

    - name: Run test
      run: make test

    - name: Run lint
      run: make lint
