name: CI

on:
  push:
  pull_request:
    branches:
      - main

# WIP
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Install dependencies
      run: make mod

    - name: Run tests
      run: make test
